### ISSUE TITLE
Maybe add some tutorial content

### ISSUE THREAD

**Issue by pwilmart** [nmclark2/TMT-NEAT#1]
Hi Natalie,
Great work. This repo and the SCION one are nice. You might want to add more to the README or make a tutorial markdown file to show screen shots of running the tools and some comments on design choices/features. I think you need to entice people to download and try software. Some overview and visuals of what will happen when the software runs reduces fear of the unknown. Also, seeing some of the cool things the software will do for the user can help get folks over the download hurdle. The tutorial content also comes in handy for seminars and any hands-on training of local users.

If you do the README updates one repo at a time, then you can tweet about each. I think the half-life for tweets is something like 20 minutes. It pays to tweet multiple times on given topics. I like to find some new context to re-tweet about something. It helps disguise the shameless self promotion. Ha-ha. 
Cheers,
Phil

**Comment by nmclark2** [comment]
Hi Phil,

Thank you very much for your feedback! I agree a tutorial is likely quite useful. One of my co-authors makes some very nice R markdowns. I'll work with him to create tutorials for these.

Best,
Natalie
