### ISSUE TITLE
Error in EnhancedVolcano

### ISSUE THREAD

**Issue by hcadre** [nmclark2/TMT-NEAT#2]
When using TMT-Neat with the test files provided, I get the following error message
![image](https://user-images.githubusercontent.com/16349515/137721246-7e825c75-7be6-42c4-969b-d4e1b6f87052.png)
and the shiny app closes. Any suggestions on how to proceed? Boxplots, line cluster and PCA plots are saved properly but Mock22_vs_Toxneg22_volcano_plot_0.1.png is empty (see error message). 
(I am running RUN-TMT.R through R4.1.0 on RStudio)

**Comment by nmclark2** [comment]
Hi @hcadre,

Thanks very much for tagging this issue! This seems to be an issue with the newest version of EnhancedVolcano. According to the help file, transcriptPointSize and transcriptLabSize have been deprecated in versions > 1.4. I have been using version 1.3. 

To fix the issue, you should change transcriptPointSize to pointSize and transcriptLabSize to labSize in lines 636 and 645 of the TMT_pseq_pipeline.R file. Re-source the function, and then run.

Please let me know if this fixes the issue, and if so, I will push the fix.

Best,
Natalie

**Comment by hcadre** [comment]
Hi Natalie, 
Many thanx for your quick reply! I changed the TMT_pseq_pipeline.R file accordingly , rerun the shiny app via RUN_TMT.R and now it whizzes through the script without any glitches! Perfect!
Best, 
Hannes

**Comment by hcadre** [comment]
Hi Natalie, 
I guess I have to weaken my previous comment somewhat: When sifting though the volcano plots generated by TMT-NEAT on the test data, I noticed that in all plots data distribution is not centered around 0 but considerably right-shifted, such as shown here:
![image](https://user-images.githubusercontent.com/16349515/137904882-fea9ecb1-a8e6-496d-99d7-36e34dfa078a.png)
This seem to happen whether Sample Loading Normalization is ticked or not. and it is probably not what you would expect. 
Best, 
Hannes

**Comment by nmclark2** [comment]
Hi Hannes,

Fantastic on the labels! I will push the fix later today. 

This slight right shift is actually what is expected for these data. Sometimes the intensities are still a little high or low after normalization. 

I am currently working on updating the test data and adding a tutorial with our published data in Nature Communications. These are nicely zero centered.
 
I'm going to close this issue, but if you run into any other problems please let me know! 

Best,
Natalie

**Comment by hcadre** [comment]
Dear Natalie, 
Got it. Thanks! I sent you another email / question - to your iastate.edu address (since this question is more related to biology and to your Nat Comm article)
Best, 
Hannes
